# Application
quarkus.http.port=8083
%prod.quarkus.http.port=8083

# Kafka Configuration (Incoming)
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
mp.messaging.connector.smallrye-kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
mp.messaging.incoming.audit-events.connector=smallrye-kafka
mp.messaging.incoming.audit-events.topic=payment-audit-log
mp.messaging.incoming.audit-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.audit-events.group.id=audit-service-group
mp.messaging.incoming.audit-events.auto.offset.reset=earliest
mp.messaging.connector.smallrye-kafka.metrics=true

# MongoDB Configuration
quarkus.mongodb.connection-string=${MONGODB_URL:mongodb://localhost:27017}
quarkus.mongodb.database=payment_audit_db

# Peformance Settings
quarkus.thread-pool.max-threads=100
mp.messaging.incoming.audit-events.max.poll.records=500

# Observability
quarkus.health.extensions.enabled=true
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.kafka.enabled=true
quarkus.micrometer.binder.http-server.percentiles-histogram=true
quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317

# GELF Logging
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=localhost
quarkus.log.handler.gelf.port=12201
quarkus.log.handler.gelf.level=INFO
