# Quarkus - Project Configuration
quarkus.application.name=payment-orchestrator

# Database (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
quarkus.hibernate-orm.database.generation=${DB_GENERATION:validate}
quarkus.hibernate-orm.log.sql=false

# Agroal Pool Tuning
quarkus.datasource.jdbc.initial-size=50
quarkus.datasource.jdbc.min-size=50
quarkus.datasource.jdbc.max-size=500
quarkus.datasource.jdbc.acquisition-timeout=PT5S

# Thread Pool Tuning
quarkus.thread-pool.max-threads=1000

# Redis Client
quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
mp.messaging.outgoing.payment-events.connector=smallrye-kafka
mp.messaging.outgoing.payment-events.topic=payment.events
mp.messaging.outgoing.payment-events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Health Checks
quarkus.health.extensions.enabled=true

# OpenTelemetry
quarkus.otel.enabled=false
# quarkus.otel.exporter.otlp.endpoint=http://localhost:4317

# Micrometer Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.publish-percentile-histogram=true
quarkus.micrometer.binder.http-server.histogram=true

# REST Client - Service Connector
quarkus.rest-client.connector-service.url=http://provider_simulator:8084/mock-provider

# Audit Configuration
audit.encryption.key=lnFzXdDiIwPPclGu3N22aeIEmBolo9ZNPnnckBRlRFE=
mp.messaging.outgoing.audit-events.connector=smallrye-kafka
mp.messaging.outgoing.audit-events.topic=payment-audit-log
mp.messaging.outgoing.audit-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# GELF Logging
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=${LOGSTASH_HOST:localhost}
quarkus.log.handler.gelf.port=12201
quarkus.log.handler.gelf.level=INFO
