{
 "title": "Service Providers Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_id",
    "label": "Service Provider",
    "query": "label_values(business_payment_seconds_count, service_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Consultas Recibidas ($service_id)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(business_inquiry_seconds_count{service_id=~\"$service_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Pagos Recibidos ($service_id)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(business_payment_seconds_count{service_id=~\"$service_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Global Transaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/payments\"}[1m]))",
     "legendFormat": "Global Throughput (TPS)"
    }
   ]
  },
  {
   "title": "Transactions by Status Code ($service_id)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(business_payment_seconds_count{service_id=~\"$service_id\"}[1m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Business Latency P99 ($service_id)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(business_payment_seconds_bucket{service_id=~\"$service_id\"}[1m])) by (le)) * 1000",
     "legendFormat": "P99 Latency (ms)"
    }
   ]
  },
  {
   "title": "Total Success vs Failure ($service_id)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(business_payment_seconds_count{service_id=~\"$service_id\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Granular Error Rate ($service_id)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(business_payment_seconds_count{status!~\"201\", service_id=~\"$service_id\"}[1m])) / sum(rate(business_payment_seconds_count{service_id=~\"$service_id\"}[1m])) * 100",
     "legendFormat": "Error Rate (%)"
    }
   ]
  }
 ]
}