import os
import json

MEMORY_FILE = os.path.join(os.path.dirname(__file__), "solved_cases.jsonl")
PLAYBOOKS_DIR = os.path.join(os.path.dirname(__file__), "playbooks")

def check_and_update_memory(ticket_id: str, failure_mode: str, action: str, description: str):
    """
    Agrega el caso resuelto al archivo. Si hubo 3 casos seguidos con el mismo 
    failure_mode, genera una regla refleja (Live Alert Rule) para optimizar LangGraph.
    """
    if not failure_mode or not action:
        return
        
    # 1. Guardar en memoria
    new_entry = {
        "ticket_id": ticket_id,
        "failure_mode": failure_mode,
        "action": action,
        "description": description
    }
    
    with open(MEMORY_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(new_entry) + "\n")
        
    # 2. Leer la memoria reciente
    history = []
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, "r", encoding="utf-8") as f:
            for line in f:
                history.append(json.loads(line))
                
    if len(history) < 3:
        return
        
    # 3. Analizar los últimos 3 (Ventana rodante de contexto)
    last_3 = history[-3:]
    all_same_failure = all(c["failure_mode"] == failure_mode for c in last_3)
    all_same_action = all(c["action"] == action for c in last_3)
    
    if all_same_failure and all_same_action and failure_mode not in ["UNKNOWN", "UNKNOWN_ERROR_REQUIRES_HUMAN", "None", "NONE"]:
        # Revisar si ya creamos un playbook reciente para esto para no spamear
        playbook_name = f"playbook_auto_REFLECTIVE_{failure_mode.upper()}.md"
        playbook_path = os.path.join(PLAYBOOKS_DIR, playbook_name)
        
        if not os.path.exists(playbook_path):
            print(f"\n🧠 [REFLECTIVE MEMORY] ¡Patrón detectado! 3 tickets seguidos clasificados como {failure_mode}.")
            print(f"🧠 Generando regla refleja temporal (Live Alert) para auto-resolver futuros incidentes...")
            
            content = f"""# LIVE ALERT RULE (Auto-Generated by Reflective Memory)
            
**Patrón Detectado:** {failure_mode}
**Acción Consensuada:** {action}

### Síntomas Recurrentes (Extraídos de la memoria a corto plazo):
- "{last_3[0]['description']}"
- "{last_3[1]['description']}"
- "{last_3[2]['description']}"

### Resolución Automatizada (RCA Action Expresa):
Ante este escenario reiterativo, la accion a tomar debe ser estricta e incontestable: `{action}`.
Al ser un error en vivo ya conocido, el confidence_score debe ser 1.0 y requires_human_approval debe ser False.
"""
            os.makedirs(PLAYBOOKS_DIR, exist_ok=True)
            with open(playbook_path, "w", encoding="utf-8") as f:
                f.write(content)
                
            print(f"🧠 ✅ Regla neuronal creada en {playbook_path}. El RAG la indexará en streaming para el próximo ticket.")
