quarkus.http.port=8084
quarkus.application.name=provider-simulator
%prod.quarkus.http.port=8084
%dev.quarkus.http.port=8084

# Thread Pool Tuning
quarkus.thread-pool.max-threads=1000

# GELF Logging
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=${LOGSTASH_HOST:localhost}
quarkus.log.handler.gelf.port=12201
quarkus.log.handler.gelf.level=INFO
quarkus.log.handler.gelf.level=INFO

# Micrometer Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.percentiles-histogram=true
